# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! ${{ env.GITHUB_RUN_ID }} >>report.md

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          {
          echo { \"name\":\"Some Report\",
          echo \"head_sha\": \"${{ github.sha }}\",
          echo \"conclusion\":\"success\",
          echo \"completed\":\"$(date --iso-8601=seconds)Z\",
          echo \"output\": {
          echo \"title\": \"some title\",
          echo \"summary\":\"$(cat data.md)\"
          echo }
          echo }
          } >> report.json
          
          
      - name: show file
        run: cat report.json
        
      - name: test json
        run: jq --version
          
      - name: Send request
        run: |
          curl \
          -X POST \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.v3+json" \
          -d @report.json \
          https://api.github.com/repos/${{ github.repository }}/check-runs          
